apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-cfg
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: ws1
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
