apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: config-poller
              containerPort: 8081
              protocol: TCP
            - name: config-setter
              containerPort: 8082
              protocol: TCP
          env:
            - name: CONTROLLER_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CONTROLLER_CONNECTION
            - name:  DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key:  MONGODB_HOSTNAME
            - name: REPLICA_SET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: REPLICA_SET
            - name: CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CONNECTION_STRING
            - name: IS_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: IS_DEBUG
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
